table_name = 'mail_accounts'
action = 'create'
[create]
    [create.id]
    primary_key = "True"
    type = "Integer"

    [create.created_at]
    default = "datetime.utcnow"
    nullable = "False"
    type = "TIMESTAMP"

    [create.updated_at]
    nullable = "False"
    onupdate = "datetime.utcnow"
    type = "TIMESTAMP"
