table_name = 'sites'
action = 'create'
[create]
    [create.id]
    primary_key = "True"
    type = "Integer"

    [create.domain]
    type = "String"
    nullable = "False"

    [create.created_at]
    default = "datetime.utcnow"
    nullable = "False"
    type = "TIMESTAMP"

    [create.updated_at]
    onupdate = "datetime.utcnow"
    type = "TIMESTAMP"

[relationship]

    [relationship.customer]
    mode = "OneToMany"
    column = "customer_id"
    table = "customers"
