table_name = 'mail_domains'
action = 'create'
[create]
    [create.id]
    primary_key = "True"
    type = "Integer"

    [create.domain]
    type = "String"
    nullable = "False"

    [create.policy]
    type = "Boolean"

    [create.dkim]
    type = "Boolean"

    [create.dkim_selector]
    type = "String"

    [create.dkim_private]
    type = "Text"

    [create.dns_record]
    type = "Text"

    [create.created_at]
    default = "datetime.utcnow"
    nullable = "False"
    type = "TIMESTAMP"

    [create.updated_at]
    onupdate = "datetime.utcnow"
    type = "TIMESTAMP"

[relationship]

[relationship.customer]
    mode = "OneToMany"
    column = "customer_id"
    table = "customers"