table_name = 'templates'
action = 'create'
[create]
    [create.id]
    primary_key = "True"
    type = "Integer"

    [create.limit_web_domain]
    type = "Integer"
    default = 0

    [create.created_at]
    default = "datetime.utcnow"
    nullable = "False"
    type = "TIMESTAMP"

    [create.updated_at]
    onupdate = "datetime.utcnow"
    type = "TIMESTAMP"
