table_name = 'customers'
action = 'create'
[create]
    [create.id]
    primary_key = "True"
    type = "Integer"
    
    [create.costumer_name]
    type = "String"
    nullable = "False"

    [create.costumer_code]
    type = "String"
    unique = "True"
    nullable = "False"

    [create.language]
    type = "String"

    [create.street]
    type = "String"

    [create.zip_code]
    type = "String"

    [create.city]
    type = "String"

    [create.state]
    type = "String"

    [create.added_by]
    type = "String"
    nullable = "False"

    [create.notes]
    type = "Text"

    [create.locked]
    type = "Boolean"
    default = "False"

    [create.canceled]
    type = "Boolean"
    default = "False"

    [create.created_at]
    default = "datetime.utcnow"
    nullable = "False"
    type = "TIMESTAMP"

    [create.updated_at]
    onupdate = "datetime.utcnow"
    type = "TIMESTAMP"

[relationship]

    [relationship.user]
    mode = "OneToOne"
    column = "user_id"
    table = "users"

    [relationship.country]
    mode = "OneToMany"
    column = "country_id"
    table = "countries"